version: 2.1
jobs:
  build-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: "execute docker build"
          command: |
            cd baserepo 
            docker build -t image .
workflows:
  build-docker-workflow:
    jobs:
      - build-docker
